### ISSUE TITLE
Fix rsolr CI process and review PRs

### ISSUE THREAD

**Issue by bess** [pulibrary/drds_catchall#10]
We use the [rsolr](https://github.com/rsolr/rsolr) gem extensively, but its maintenance is currently being neglected. Jonathan Rochkind is currently trying to add a solr timeout setting to Blacklight, but that will require that RSolr knows about and respects that setting. The following is in support of that feature, which would be useful to us at Princeton.

- [x] Fix the CI build (currently giving an SSLError)
- [ ] Review these PRs:
  - [ ] https://github.com/rsolr/rsolr/pull/215
  - [x] https://github.com/rsolr/rsolr/pull/214
- [ ] Tag a new release
- [ ] Upgrade our systems to use the new release

**Comment by hectorcorrea** [comment]
We pushed this out of the Maple Leaf milestone with the intention of making it a priority on the next one (Sprint 11/22-12/3)

**Comment by bess** [comment]
This is done.
