### ISSUE TITLE
Import HR feed for students and advisors into production

### ISSUE THREAD

**Issue by kelynch** [pulibrary/drds_catchall#112]
Based on [this timeline](https://docs.google.com/document/d/1glTeD7gl90ABKYHZ_I5ZqzDuQvug4UKrNMtZCqMjtLA/edit).

Between Feb 13 and 17

**Comment by jrgriffiniii** [comment]
While the HR feed has been imported, there exist some anomalous submission entries which must be manually removed.

**Comment by jrgriffiniii** [comment]
The student submissions have been successfully imported into the `production` environment.
