### ISSUE TITLE
Refresh production HR feed for students and advisors for public launch

### ISSUE THREAD

**Issue by kelynch** [pulibrary/drds_catchall#113]
Based on [this timeline](https://docs.google.com/document/d/1glTeD7gl90ABKYHZ_I5ZqzDuQvug4UKrNMtZCqMjtLA/edit).

Between Mar 6 and 10

**Comment by kelynch** [comment]
Blocked by #110, #111, and #112.

**Comment by jrgriffiniii** [comment]
This has been fully refreshed within the production environment.
