### ISSUE TITLE
[thesis-central] Provide OIT Service Accounts for the Windows Bastion Host

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/drds_catchall#117]
Acceptance Criteria:

- [ ] Document the form(s) required to request a new OIT Service Account for Windows hosts
- [ ] RDSS colleagues should be able successfully request OIT Service Accounts
- [ ] RDSS colleagues should have downloaded a supported RDP client used to authenticate against the Windows bastion host
- [ ] RDSS colleagues should be able to successfully authenticate against the Windows bastion host

**Comment by bess** [comment]
Process documented in the video but we're not doing this now.
