### ISSUE TITLE
[thesis-central] Provide OIT Service Accounts for Accessing the AWS Hosts for Thesis Central QA and prod Environments

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/drds_catchall#118]
Acceptance Criteria:

- [ ] RDSS colleagues should be able to authenticate against the Windows bastion host
- [ ] RDSS colleagues should be able to identify and execute the PuTTY client on the Windows bastion host
- [ ] RDSS colleagues should, using PuTTY, be able to authenticate and access the thesis-central QA infrastructure
- [ ] RDSS colleagues should on thesis-central QA infrastructure have the ability to acquire `root` privileges
- [ ] RDSS colleagues should, using PuTTY, be able to authenticate and access the thesis-central prod infrastructure
- [ ] RDSS colleagues should on thesis-central prod infrastructure have the ability to acquire `root` privileges

**Comment by bess** [comment]
Documented in the video.
