### ISSUE TITLE
[dataspace] Staging environment server required a password update for the database server user

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/drds_catchall#127]

**Comment by kelynch** [comment]
This is completed.

**Comment by jrgriffiniii** [comment]
Please note that this was modified through the Google Cloud Platform dashboard at the following:
<img width="1858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNC9GQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4230f7f9c42b897c83b1425681c6f0cba6ce7514/image.png" alt="image.png" />
