### ISSUE TITLE
thesis central prod is down

### ISSUE THREAD

**Issue by bess** [pulibrary/drds_catchall#129]
<img width="1858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlhhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85ed628ba40c93f015d441fea502c5a62de3acc7/Screenshot%202024-07-14%20at%208.31.44%E2%80%AFPM.png" alt="Screenshot 2024-07-14 at 8.31.44 PM.png" />

**Comment by jrgriffiniii** [comment]
The service has been restored, however, I am looking now to diagnose the root cause of the errors.
