### ISSUE TITLE
Decommission legacy Vireo servers

### ISSUE THREAD

**Issue by kelynch** [pulibrary/drds_catchall#136]
As the service is moving to hosted DSpace, decommission the Vireo servers hosted by OIT.

Servers:
* libtc101l
* libtc103l
* libtc201l 
* libtc203l

Note: Backups for 2024 theses export packages from Vireo are in S3 in a dark archive.

**Comment by kelynch** [comment]
Email sent to OIT contacts who manage these servers requesting decommissioning.

**Comment by kelynch** [comment]
Ticket created at RITM0581677

**Comment by jrgriffiniii** [comment]
At the request of a colleague in the OIT, please know that INC0612399 tracks the request to have all legacy ThesisCentral servers removed from Nagios and ThousandEyes alerts.

**Comment by kelynch** [comment]
According to OIT, 6 days ago:

"All four servers have been shutdown. Decommission process will begin after next week." 

Closing this ticket.
