### ISSUE TITLE
Move docs about creating a service account to main IT handbook

### ISSUE THREAD

**Issue by bess** [pulibrary/drds_catchall#137]
We currently have documentation about how to create a service account, but it is in the Globus handbook entry for RDSS. Instead, move this to its own spot under the main IT handbook, and reference that document from the Globus entry.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/rdss-catchall/137?planning-poker) with Zenhub @bess @hectorcorrea @JaymeeH @leefaisonr
