### ISSUE TITLE
Complete offboarding tasks for 20LM22

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/drds_catchall#144]
This tracks the steps provided in the Student Employee Offboarding document:

https://github.com/pulibrary/pul-it-handbook/blob/main/student-software-developers/administration-handbook/offboarding.md

- [ ] Student computers should be returned to Tracy Hall for her team to reimage for the next group of student developers with 3 weeks of lead time if possible
- [ ] Create an lsupport ticket when they’re ready to be reimaged
- [X] As they are leaving their position before the end of a term, the following form must be completed: https://princeton.studentemployment.ngwebsolutions.com/Cux_ContactDetail.aspx?PurposeId=22

**Comment by carolyncole** [comment]
FYI I asked @matthewjchandler to remove her from the user list for tigerdata.  I noticed she was in there.

**Comment by jrgriffiniii** [comment]
The laptop is scheduled to be returned during the week of 12/16/24
