### ISSUE TITLE
Empty and reseed ThesisCentral database for class of 2021 (production)

### ISSUE THREAD

**Issue by kelynch** [pulibrary/drds_catchall#25]
Upon acceptance by Lynn, empty and reseed the thesiscentral production database with HR people feed (James, Bess, and Kate all receive this twice a week) based on instructions in the [readme](https://github.com/PrincetonUniversityLibrary/thesiscentral-vireo/blob/d3347a091ee69793f498acd4df7ffb0aaeba2dc7/README.md#princeton-modifications).

## Acceptance Criteria

- [x] Database contains no 2020 data
- [x] Database contains all 2021 student data with modified email addresses
- [ ] RDSS staff and Lynn can log in

**Comment by jrgriffiniii** [comment]
It might be prudent to note that this consumed approximately 3 hours (but this requires that only *I* do this, as one requires extensive permissions for two OIT service account).

**Comment by jrgriffiniii** [comment]
This has been completed and is prepared for testing and review by 
@bess, @kelynch, and Lynn Durgin: https://thesis-central.princeton.edu/

**Comment by jrgriffiniii** [comment]
Unless we receive feedback from the users indicating that there are errors, this should be considered resolved.
