### ISSUE TITLE
Design a user interface component indicating that ThesisCentral Submission records are being submitted

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/drds_catchall#29]
This is in response to a user report:

> During the "Confirm & Submit" there is not a way to know that it is processing. I ended up hitting the button a number of times before I saw it was processing in the tab. Then I got this - "Oops, an error occured This exception has been logged with id 7j3co0053."

The deliverable for this should be a wireframe or some prototype of the design to be implemented in a new update for ThesisCentral.

**Comment by kelynch** [comment]
Outdated, closing per discussion within IT
