### ISSUE TITLE
Implement a user interface component indicating that ThesisCentral Submission records are being submitted

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/drds_catchall#30]
This implements the feature and user interface updates proposed within #29.

**Comment by jrgriffiniii** [comment]
Please note that https://github.com/PrincetonUniversityLibrary/pul-vireo contains the latest updates, and should please be used as the repository for active development.

**Comment by kelynch** [comment]
Outdated, closing per discussion within IT
