### ISSUE TITLE
Correct the spelling of the text "occurred " for ThesisCentral (Vireo) rendered on Submission form pages

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/drds_catchall#31]
This is in response to a report from a user:

> During the "Confirm & Submit" there is not a way to know that it is processing. I ended up hitting the button a number of times before I saw it was processing in the tab. Then I got this - "Oops, an error occured This exception has been logged with id 7j3co0053." 

> As a follow up to that error. Occurred is spelled wrong.

**Comment by jrgriffiniii** [comment]
Please note that https://github.com/PrincetonUniversityLibrary/pul-vireo contains the latest updates, and should please be used as the repository for active development.

**Comment by kelynch** [comment]
Outdated, closing per discussion within IT
