### ISSUE TITLE
Vireo 4 users can authenticate with Shibboleth

### ISSUE THREAD

**Issue by bess** [pulibrary/drds_catchall#32]
Now that the box has shibboleth authentication, we need to get the Vireo application to allow users to log in using it. At the moment, everyone who authenticates with Shibboleth gets a sample user called Jack Daniels.

**ACCEPTANCE CRITERIA**
- [ ] I can authenicate with Princeton shibboleth and it will create a Vireo account with my credentials

**Comment by jrgriffiniii** [comment]
This is a prerequisite to actually being able to submit an item using Vireo 4.

**Comment by bess** [comment]
Useful thread here: https://github.com/TexasDigitalLibrary/Vireo/issues/1414
