### ISSUE TITLE
Vireo 4 Import of Department/Certificate Programs

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/drds_catchall#33]
**ACCEPTANCE CRITERIA**
- [ ] When submitting a thesis, a student is prompted to select a department from the following controlled vocabulary

![Screen Shot 2022-02-01 at 1 49 04 PM](https://user-images.githubusercontent.com/65608/152034347-5888f21d-5df1-4b03-82af-8758a62ea50f.png)

**Comment by bess** [comment]
Update: Progress slightly derailed by figuring out how best to create admin accounts and why they aren't being read from the config file as expected.

**Comment by bess** [comment]
![Screen Shot 2022-02-02 at 5 06 18 PM](https://user-images.githubusercontent.com/65608/152245523-55c25542-6836-4ba1-92e2-eeb048106c48.png)
