### ISSUE TITLE
Vireo 4 Branding Customization for the Deployment

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/drds_catchall#34]
By default, the Vireo 4 installation is going to have generic branding (which also references Texas Digital Library). The branding should closely match what is currently found on ThesisCentral.

**ACCEPTANCE CRITERIA**
- [ ] All references to the Texas Digital Library should be removed
- [ ] One should match the head banner to the PUL branding
- [ ] One should match the footer to the PUL branding

**Comment by jrgriffiniii** [comment]
Please see the following for reference: ![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/4057e00f-5624-4198-b991-93faab328314)

**Comment by kelynch** [comment]
Closing per discussion within IT
