### ISSUE TITLE
Shibboleth login should create account with correct field values

### ISSUE THREAD

**Issue by bess** [pulibrary/drds_catchall#37]
Currently, when a user authenticates with Shibboleth to Vireo 4, their name is always "null null" because the shibboleth attributes aren't being mapped to their vireo account correctly. 

**ACCEPTANCE CRITERIA**
- [x] Update the shibboleth field name mappings so every user has a correctly recorded netid, email, first name, and last name

<img width="556" alt="Screen Shot 2022-01-25 at 9 58 35 AM" src="https://user-images.githubusercontent.com/65608/151001093-61084289-c58d-4872-b91b-b82ad73a4aab.png">

**Comment by bess** [comment]
<img width="817" alt="Screen Shot 2022-01-27 at 2 00 35 PM" src="https://user-images.githubusercontent.com/65608/151431410-203198c3-d54a-4886-ae65-68108c13bdc7.png">

🎉

**Comment by jrgriffiniii** [comment]
This has been resolved!
