### ISSUE TITLE
Import 2021 dissertations from ProQuest

### ISSUE THREAD

**Issue by bess** [pulibrary/drds_catchall#38]
Import latest batch of dissertations into DataSpace

**Comment by bess** [comment]
As of 1/27 there are no dissertations in the SFTP drop box. I have asked Lynn whether she wants us to follow up with ProQuest.

**Comment by bess** [comment]
ProQuest says they cannot connect to our system since 25 Jan 2021:

```
Hi Bess,

Thanks for reaching back out. It looks like this is the most recent update from the dev Team:

"It does look like there have been failures since attempting to deliver starting 1/25.  I checked the connection and am getting this:

Connecting to proquestdrop.pulcloud.io...
no hostkey alg
Couldn't read packet: Connection reset by peer"

What are your current settings?

Sincerely,
Carl
```

That `No hostkey alg` makes me wonder if we need to fix some settings in our sshd, per this stackexchange thread:

https://unix.stackexchange.com/questions/679451/sshd-no-hostkey-alg-fixed-but-still-confused

**Comment by bess** [comment]
Based on the above thread, I connected to the system and manually edited `/etc/ssh/sshd_config` to ensure that we use an RSA hostkey (previously all hostkey configuration was commented out), and that the RSA hostkey algorithm is explicitly configured. I've asked ProQuest to try again, and if it still isn't working I've requested an appointment for a real-time phone call to troubleshoot.

**Comment by kayiwa** [comment]
default behavior of OpenSSH is not to load [HostCertificate](https://man.openbsd.org/sshd_config) This suggests the client initiating the request is the likely source of the problem. The change will generate a MITM warning that can be ignored or if paranoid can ask us for verification.

**Comment by bess** [comment]
As of 2/8, ProQuest says they can now connect to our SFTP server, but I'm still not seeing any files. I've asked them for clarification.

**Comment by jrgriffiniii** [comment]
Contacting Alexis Antracoli might be the next step in order to see about escalating the priority of this with Lynn.
