### ISSUE TITLE
Build a robust Globus production service

### ISSUE THREAD

**Issue by bess** [pulibrary/drds_catchall#46]
We need a production level globus infrastructure. It needs:

- [x] a plan for storage. Is this AWS S3, or on-prem storage? Something else?
- [x] make the process of building the Globus endpoint easily repeatable
- [x] The infrastructure and workflows are well-documented in the RDSS Handbook
- [x] an ansible built server that installs the globus connector
- [x] a monitoring solution
- [x] a process for moving existing globus data
- [x] sample object(s) with globus data has been moved to the new endpoint and is accessible via PDC Discovery
- [x] a plan for where to put and how to name post-curated large research data
- [x] When we've all agreed on the plan, ensure it is documented and/or linked to here: https://docs.google.com/document/d/13HkbOoC7OLD70FIEwFlHs8zi2Z8h53Puflm7DCcjnSw/edit#

**Comment by hectorcorrea** [comment]
See also https://drive.google.com/file/d/1EnGDBMtc7LAYGj5Yk2ZLP-HtQPxIxcR0/view?usp=sharing

**Comment by bess** [comment]
I'm going to work my way through this tutorial and learn more about managing content in S3 buckets: https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/s3-examples.html
