### ISSUE TITLE
RDSS people need sensu access

### ISSUE THREAD

**Issue by bess** [pulibrary/drds_catchall#50]
Ensure the following people are in the right LDAP group to be able to see data in sensu:

- [x] Kate
- [x] James
- [x] Hector
- [x] Bess bs3097
- [x] Carolyn

**Comment by acozine** [comment]
Done. Please ping me on slack if you still don't see data in our [Sensu instance](https://lib-monitor.princeton.edu). Note: you must log in with your NetID alone (do not add `@princeton.edu`), your password, and a 2FA code. If you have push 2FA by default, check for the push quickly to avoid timeouts. If you don't have push 2FA by default, you can also use `append` mode to add your 2FA code with this pattern: `my_password,2FA`, for example `changeme,2345678`.
