### ISSUE TITLE
Import September 2022 dissertations by October 14

### ISSUE THREAD

**Issue by bess** [pulibrary/drds_catchall#76]
From 30 September email: 

Dear Kate, Bess and James,
 
Attached please find the list of Sept. 2022 dissertations that will shortly be arriving for import to DataSpace. Would it be possible for this batch to be imported by October 14? A professor would like his class to have access to one of the dissertations.  
 
Please note, in this batch will be one master's thesis which is there mistakenly. The author is Ramsurrun, Sheetal. Could we either not import this item, or import it and then deleted it immediately? (I can do this if you ping me when they are imported.) We can request this master’s thesis to be delivered individually once we have created a Master’s degree community and collection for this department.
 
Thank you,
Lynn
 
Lynn M. Durgin
Pronouns: she/her/hers
Collections Coordinator

## Acceptance criteria
- [x] Check that the files have been delivered to the SFTP service
- [x] Remove the master's thesis by Ramsurrun from the file list
- [x] Import dissertations to DSpace (instructions at https://pulibrary.github.io/etd_transformer/process-dissertations.html)
- [x] Let Lynn know it is done

[https://app.zenhub.com/files/412542172/5ba8f8c5-685a-49d2-8d09-5e574cf19d8c/download](https://app.zenhub.com/files/412542172/5ba8f8c5-685a-49d2-8d09-5e574cf19d8c/download)

**Comment by bess** [comment]
I imported what was in our SFTP dropbox, but that gave me 140 objects, while there are only 139 in the spreadsheet Lynn sent.

I sent this email to Lynn: 

Dear Lynn,

I’ve imported the dissertations as requested. There does appear to be a discrepancy, though.

The spreadsheet you sent has 139 doctoral dissertations in it. However, I downloaded and imported 140 objects from ProQuest, after I removed the Ramsurrun thesis. 

Is it possible that ProQuest sent over an extra work that isn’t listed on the spreadsheet? I’m unsure how to find it except to go through line by line. Is this a thing you’ll find as you quality check the import? What do you advise?

Thank you,
Bess

**Comment by hectorcorrea** [comment]
Closed because Lynn said it is fine. There was one additional dissertation that has been accounted for.
