### ISSUE TITLE
Rotate all our circleCI keys

### ISSUE THREAD

**Issue by bess** [pulibrary/drds_catchall#84]
Document what has been done here: https://github.com/PrincetonUniversityLibrary/security/issues/12

**Comment by carolyncole** [comment]
Since I understand how to, I am going through each project and deleting the deploy key and recreating one.
I can not quite remember how to create the Coverall Key, so I am skipping that for the moment.

**Comment by carolyncole** [comment]
All github deploy keys have been rotated.  There are still some coverall keys in place for:

- [x] [pdc_describe](https://app.circleci.com/settings/project/github/pulibrary/pdc_describe/environment-variables?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fpulibrary%2Fpdc_describe)
- [x] [pdc_discovery](https://app.circleci.com/settings/project/github/pulibrary/pdc_discovery/environment-variables?return-to=https%3A%2F%2Fapp.circleci.com%2Fprojects%2Fproject-dashboard%2Fgithub%2Fpulibrary%2F)
- [x] [cicognara-rails](https://app.circleci.com/settings/project/github/pulibrary/cicognara-rails/environment-variables?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fpulibrary%2Fcicognara-rails)
- [x] [etd_transformer](https://app.circleci.com/settings/project/github/pulibrary/etd_transformer/environment-variables?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fpulibrary%2Fetd_transformer)

**Comment by carolyncole** [comment]
I believe all our repos have been completed
